apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eksclusterconfigs.eks.cattle.io
spec:
  group: eks.cattle.io
  version: v1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            kubernetesVersion:
              type: string
            secretsEncryption:
              type: boolean
            kmsKey:
              type: string
            publicAccess:
              type: boolean
            privateAccess:
              type: boolean
            cloudCredential:
              type: string
            virtualNetwork:
              type: string
            displayName:
              type: string
            subnets:
              type: array
              items: {
                type: string
              }
            securityGroups:
              type: array
              items: {
                type: string
              }
            loggingTypes:
              type: array
              items: {
                type: string
              }
            serviceRole:
              type: string
            region:
              type: string
            imported:
              type: boolean
              enum: [true]
              nullable: true
          anyOf:
          - required: ["kubernetesVersion", "publicAccess", "privateAccess"]
          - required: ["imported"]
        status:
          type: object
          properties:
            phase:
              type: string
  subresources:
    status: {}
  scope: Namespaced
  names:
    plural: eksclusterconfigs
    singular: eksclusterconfig
    kind: EKSClusterConfig
    shortNames:
    - ekscc
