name: Update EKS Operator in rancher/charts
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch to use for GitHub action workflow"
        required: true
        default: "main"
      charts_ref:
        description: "Submit PR against the following rancher/charts branch (e.g. dev-v2.7)"
        required: true
        default: "dev-v2.7"
      prev_eks_operator:
        description: "Previous EKS operator version (e.g. 1.1.0-rc2)"
        required: true
        default: ""
      new_eks_operator:
        description: "New EKS operator version"
        required: true
        default: ""
      prev_chart:
        description: "Previous Rancher Chart version (e.g. 101.1.0)"
        required: true
        default: ""
      new_chart:
        description: "New Rancher Chart version"
        required: true
        default: ""
      should_replace:
        description: "Should the old EKS operator version be replaced/removed? (e.g. true in case of release candidate bumps)"
        required: true
        default: "true"

jobs:
  create-rancher-charts-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.inputs.ref}}
          path: eks-operator
      - name: Checkout rancher/charts
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: rancher/charts
          ref: ${{github.event.inputs.charts_ref}}
          path: charts
      - name: Run release script
        run: ./eks-operator/.github/scripts/update-rancher-charts.sh ${{github.event.inputs.prev_eks_operator}} ${{github.event.inputs.new_eks_operator}} ${{github.event.inputs.prev_chart}}  ${{github.event.inputs.new_chart}}  ${{github.event.inputs.should_replace}}
      - name: Set timestamp
        run: echo "TIMESTAMP=$(date +'%s')" >> "$GITHUB_ENV"
      - name: Create PR
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{secrets.CI_BOT_TOKEN}}
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'highlander-ci-bot/charts:${{github.event.inputs.new_eks_operator}}-$TIMESTAMP',
              base: ${{github.event.inputs.charts_ref}},
              title: 'Update EKS operator to v${{github.event.inputs.new_eks_operator}}',
              body: 'Update EKS operator to v${{github.event.inputs.new_eks_operator}}\n\nChangelog: https://github.com/rancher/eks-operator/releases/tag/v${{github.event.inputs.new_eks_operator}}\n\ncc @rancher/highlander'
            })